version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    #<puerto a exponer>: <puerto  del dokerfile>
      - "3027:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge